name: PHP vipar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Buil project to prod
      run: |
        pwd
        rsync -azvh --exclude '.git' --exclude '.github' --exclude '.idea' --exclude 'config.php' --exclude 'admin/config.php' -e "ssh -o StrictHostKeyChecking=no" . root@45.94.157.126:/var/www/vipar
        ssh -o StrictHostKeyChecking=no root@45.94.157.126 'chown -R www-data:www-data /var/www/vipar && chmod -R 755 /var/www/vipar'
        ssh -o StrictHostKeyChecking=no root@45.94.157.126 '/etc/init.d/apache2 restart'
